#!/usr/bin/env bash
# Confugration IP home and facebook

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
fi

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

cat /etc/hosts
